lukisan/urls.py
from django.contrib import admin
from django.urls import *
from .views import *

app_name='lukisan'
urlpatterns = [
    path('', index, name='index'),
    path('login_page/', login_page, name='login_page'),
    path('pengguna/penyewa/', penyewa, name='penyewa'),
    path('pengguna/pemilik/', pemilik, name='pemilik'),
    path('pengguna/staf/', staf, name='staf'),
    path('page_lukisan/', page_lukisan, name='page_lukisan'),
    path('transaksi/sewa', sewa, name='sewa'),
    path('transaksi/fee', fee_func, name='fee'),
    path('transaksi/mitra', mitra, name='mitra'),
]

tk_basdat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lukisan.urls')),
]

lukisan/models.py
from django.db import models

# Create your models here.

lukisan/views.py
from django.shortcuts import render
from django.urls import reverse
import psycopg2
import request
from django.http import response

def index(request):
	response = {}
	return render(request, 'index.html', response)

def login_page(request):
	response = {}
	return render(request, 'login_page.html', response)

# def penyewa(request):
# 	response = {}
# 	return render(request, 'penyewa.html', response)

# def pemilik(request):
# 	response = {}
# 	return render(request, 'pemilik.html', response)

def pemilik(request): #utk ngambul tgl pemesanan, no pelanggan, id sewa
    context = {}
    try:
        connection = psycopg2.connect(user="qbnhvcwi",
                                        password="NBGODrUBuhITqs7h6fZ6T-6T_vw-nprT",
                                        host="rajje.db.elephantsql.com",
                                        port="5432")
        cursor = connection.cursor()
        postgreSQL_select_Query = "select pl.id_pelanggan, pl.nama, pl.no_hp, pl.ttl, pl.no_ktp, pl.email, pl.alamat, pm.no_rek, pm.nama_bank from pelanggan as pl join pemilik as pm on pl.id_pelanggan = pm.id_pelanggan"
        postgreSQL_select_Querysp = "set search_path to penyewaanlukisan"

        cursor.execute(postgreSQL_select_Querysp)
        cursor.execute(postgreSQL_select_Query)

        context["pengguna"] = cursor.fetchall()
        print(type(response))
        print(response)

    except (Exception, psycopg2.Error) as error :
        print ("Error while fetching data from PostgreSQL", error)

    finally:
        if(connection):
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")
    return render(request, 'pemilik.html', context)

def penyewa(request): #utk ngambul tgl pemesanan, no pelanggan, id sewa
    context = {}
    try:
        connection = psycopg2.connect(user="qbnhvcwi",
                                        password="NBGODrUBuhITqs7h6fZ6T-6T_vw-nprT",
                                        host="rajje.db.elephantsql.com",
                                        port="5432")
        cursor = connection.cursor()
        postgreSQL_select_Query = "select pl.id_pelanggan, pl.nama, pl.no_hp, pl.ttl, pl.no_ktp, pl.email, pl.alamat, py.pekerjaan, py.kategori from pelanggan as pl join penyewa as py on pl.id_pelanggan = py.id_pelanggan"
        postgreSQL_select_Querysp = "set search_path to penyewaanlukisan"

        cursor.execute(postgreSQL_select_Querysp)
        cursor.execute(postgreSQL_select_Query)

        context["pengguna"] = cursor.fetchall()
        print(type(response))
        print(response)

    except (Exception, psycopg2.Error) as error :
        print ("Error while fetching data from PostgreSQL", error)

    finally:
        if(connection):
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")
    return render(request, 'penyewa.html', context)

def staf(request):
	response = {}
	return render(request, 'staf.html', response)

def page_lukisan(request):
    context = {}
    try:
        connection = psycopg2.connect(user="qbnhvcwi",
                                        password="NBGODrUBuhITqs7h6fZ6T-6T_vw-nprT",
                                        host="rajje.db.elephantsql.com",
                                        port="5432")
        cursor = connection.cursor()
        postgreSQL_select_Query = "select id_lukisan, nama_lukisan, tema_lukisan, harga, tahun, id_pelanggan from lukisan "
        postgreSQL_select_Querysp = "set search_path to penyewaanlukisan"

        cursor.execute(postgreSQL_select_Querysp)
        cursor.execute(postgreSQL_select_Query)

        context["transaksi"] = cursor.fetchall()
        print(type(response))
        print(response)
        

    except (Exception, psycopg2.Error) as error :
        print ("Error while fetching data from PostgreSQL", error)

    finally:
        #closing database connection.
        if(connection):
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")
    return render(request, 'page_lukisan.html', context)

def sewa(request):
	response = {}
	return render(request, 'sewa.html', response)

def fee(request):
	response = {}
	return render(request, 'fee.html', response)

def mitra(request):
	response = {}
	return render(request, 'mitra.html', response)

def fee_func(request): #utk ngambul tgl pemesanan, no pelanggan, id sewa
    context = {}
    try:
        connection = psycopg2.connect(user="qbnhvcwi",
                                        password="NBGODrUBuhITqs7h6fZ6T-6T_vw-nprT",
                                        host="rajje.db.elephantsql.com",
                                        port="5432")
        cursor = connection.cursor()
        postgreSQL_select_Query = "select ts.tgl_sewa, ts.id_pelanggan, ts.banyaknya, ts.id_lukisan, l.harga, bs.total_biaya from biaya_sewa bs join transaksi_sewa ts on bs.id_pelanggan = ts.id_pelanggan join lukisan l on ts.id_lukisan = l.id_lukisan "
        postgreSQL_select_Querysp = "set search_path to penyewaanlukisan"

        cursor.execute(postgreSQL_select_Querysp)
        cursor.execute(postgreSQL_select_Query)

        context["transaksi"] = cursor.fetchall()
        print(type(response))
        print(response)

    except (Exception, psycopg2.Error) as error :
        print ("Error while fetching data from PostgreSQL", error)

    finally:
        #closing database connection.
        if(connection):
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")
    return render(request, 'fee.html', context)

#Untuk mengambil data transaksi
def sewa(request):
    context = {}
    try:
        connection = psycopg2.connect(user="qbnhvcwi",
                                        password="NBGODrUBuhITqs7h6fZ6T-6T_vw-nprT",
                                        host="rajje.db.elephantsql.com",
                                        port="5432")
        cursor = connection.cursor()
        postgreSQL_select_Query = "select ts.tgl_sewa, ts.tgl_kembali, ts.banyaknya, ts.lama_sewa, ts.no_staff, p.nama, l.nama_lukisan from transaksi_sewa ts join pelanggan p on ts.id_pelanggan = p.id_pelanggan join lukisan l on ts.id_lukisan = l.id_lukisan"
        postgreSQL_select_Querysp = "set search_path to penyewaanlukisan"

        cursor.execute(postgreSQL_select_Querysp)
        cursor.execute(postgreSQL_select_Query)
       # print("Selecting rows from mobile table using cursor.fetchall")
        context["transaksi"] = cursor.fetchall()
        print(type(response))
        print(response)
        
        # print("Print each row and it's columns values")
        # for row in response:
        #     print("tgl_terima = ", row[0], )
        #     print("jumlah = ", row[1])
        #     print("id_pelanggan  = ", row[2], "\n")

    except (Exception, psycopg2.Error) as error :
        print ("Error while fetching data from PostgreSQL", error)

    finally:
        #closing database connection.
        if(connection):
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")
    return render(request, 'sewa.html', context)

#Untuk mengambil data staff
def staf(request):
    context = {}
    try:
        connection = psycopg2.connect(user="qbnhvcwi",
                                        password="NBGODrUBuhITqs7h6fZ6T-6T_vw-nprT",
                                        host="rajje.db.elephantsql.com",
                                        port="5432")
        cursor = connection.cursor()
        postgreSQL_select_Query = "select s.no_staff, s.nama, s.ttl, sl.lulusan_staff, s.no_hp, s.email from staff s join staff_lulusan sl on s.no_staff = sl.no_staff"
        postgreSQL_select_Querysp = "set search_path to penyewaanlukisan"

        cursor.execute(postgreSQL_select_Querysp)
        cursor.execute(postgreSQL_select_Query)
       # print("Selecting rows from mobile table using cursor.fetchall")
        context["staf"] = cursor.fetchall()
        print(type(response))
        print(response)
        
        # print("Print each row and it's columns values")
        # for row in response:
        #     print("tgl_terima = ", row[0], )
        #     print("jumlah = ", row[1])
        #     print("id_pelanggan  = ", row[2], "\n")

    except (Exception, psycopg2.Error) as error :
        print ("Error while fetching data from PostgreSQL", error)

    finally:
        #closing database connection.
        if(connection):
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")
    return render(request, 'staf.html', context)

#Untuk mengambil data staff
def mitra(request):
    context = {}
    try:
        connection = psycopg2.connect(user="qbnhvcwi",
                                        password="NBGODrUBuhITqs7h6fZ6T-6T_vw-nprT",
                                        host="rajje.db.elephantsql.com",
                                        port="5432")
        cursor = connection.cursor()
        postgreSQL_select_Query = "select kode_bank, nama_bank from mitra_bank"
        postgreSQL_select_Querysp = "set search_path to penyewaanlukisan"

        cursor.execute(postgreSQL_select_Querysp)
        cursor.execute(postgreSQL_select_Query)
       # print("Selecting rows from mobile table using cursor.fetchall")
        context["mitra"] = cursor.fetchall()
        print(type(response))
        print(response)
        
        # print("Print each row and it's columns values")
        # for row in response:
        #     print("tgl_terima = ", row[0], )
        #     print("jumlah = ", row[1])
        #     print("id_pelanggan  = ", row[2], "\n")

    except (Exception, psycopg2.Error) as error :
        print ("Error while fetching data from PostgreSQL", error)

    finally:
        #closing database connection.
        if(connection):

lukisan/templates/base.html
{% load static %}
<div>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark">
        <a class="navbar-brand" href="{% url 'lukisan:index' %}">
            <img style="height: 50px;" src="/static/images/logo.png" %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="padding-right: 30px;">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color:black;" href="{% url 'lukisan:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PENGGUNA</a>
                    
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'lukisan:penyewa' %}">Penyewa</a>
                        <a class="dropdown-item" href="{% url 'lukisan:pemilik' %}">Pemilik</a>
                        <a class="dropdown-item" href="{% url 'lukisan:staf' %}">Staf</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" style="color:black;" href="{% url 'lukisan:page_lukisan' %}">LUKISAN</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color:black;" href="{% url 'lukisan:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">TRANSAKSI</a>
                    
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'lukisan:sewa' %}">Sewa</a>
                        <a class="dropdown-item" href="{% url 'lukisan:fee' %}">Fee</a>
                        <a class="dropdown-item" href="{% url 'lukisan:mitra' %}">Mitra</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" style="color:black;" href="{% url 'lukisan:index' %}">Logout</a>
                </li>

            </ul>
        </div>
    </nav>
</div>

lukisan/templates/base_index.html
{% load static %}
<div>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark">
        <a class="navbar-brand" href="{% url 'lukisan:index' %}">
            <img style="height: 50px;" src="/static/images/logo.png" %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="padding-right: 30px;">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" style="color:black;" href="{% url 'lukisan:login_page' %}">Login</a>
                </li>

            </ul>
        </div>
    </nav>
</div>

lukisan/templates/fee.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Data Transaksi Fee</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
    <div class="container-fluid header">
        {%include "base.html"%}
    </div>
    <br>
    <br>

    <!-- {% for row in transaksi %}
    {% for item in row %}
    {{item}}
    {% endfor %}
    br>
    3{% endfor %} -->

    <div class="text-center">
        <h3>RIWAYAT TRANSAKSI</h3>
    </div>


    <div class="table-responsive" style="width:90%; margin:0 auto;">
        <table class="table mt-4">
            <thead class="text-dark">
                <tr>
                    <th>Tgl Pemesanan</th>
                    <th>Nomor Pelanggan</th>
                    <th>ID Lukisan</th>
                    <th>Jumlah Sewa</th>
                    <th>Harga Lukisan</th>
                    <th>Total Fee</th>
                </tr>
            </thead>

            <tbody class="text-muted">
                {% for row in transaksi %}
                <tr>
                    <td>{{ row.0 }}</td>
                    <td>{{ row.1 }}</td>
                    <td>{{ row.2 }}</td>
                    <td>{{ row.3 }}</td>
                    <td>{{ row.4 }}</td>
                    <td>{{ row.5 }}</td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>

</body>

</html>

lukisan/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>silukisan.com</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
</head>
<body>
	<div class="container-fluid header">
		{%include "base_index.html"%}
	</div>

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
    
        
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="/static/images/img_1.jpeg" alt="First slide">
            </div>
        
            <div class="carousel-item">
                <img class="d-block w-100" src="/static/images/img_2.jpeg" alt="Second slide">
            </div>
      
            <div class="carousel-item">
                <img class="d-block w-100" src="/static/images/img_3.jpeg" alt="Third slide">
            </div>
        </div>
    
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
    
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="container text-center text-welcome" style="margin-top: 50px;">
        <h1>SELAMAT DATANG DI</h1>

        <h1>SILUKISAN.com</h1>

        <p>"Kami merupakan perusahaan jasa penyewa lukisan dengan kualitas terbaik"</p>
    </div>

    <footer class="container-fluid footer">
    </footer>

</body>
</html>

lukisan/templates/login_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>login</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
	<style>
		.form-login {
			margin-top: 8%;
			width: 28%;
		}

		.judul {
			margin-top: 10%;
		}

	</style>

	<h1 class="judul text-center">Selamat Datang Di Silukisan.com</h1>

	<div class="container-fluid form-login">
		{% block body %}
			<div class="card shadow-lg">
				<h5 class="card-header">Login</h5>
				<div class="card-body">			
					{% if message %}
						<div class="alert alert-danger" role="alert">
							{{message}}
						</div>
					{% endif %}

					<form action="" method="POST">
						{% csrf_token %}
						<div class="form-group">
							<label>Nomor Staf</label>
							<input type="text" class="form-control" name="login_nostaf" required>
						</div>
						<div class="form-group">
							<label>Email</label>
							<input type="text" class="form-control" name="login_email" required>
						</div>
						<div class="form-group">
							<a class="btn btn-success" href="{% url 'lukisan:penyewa' %}">Login</a>
						</div>
						<small class="form-text">Belum punya akun? <a href="">Registrasi</a></small>
					</form>	
				</div>
			</div>
		{% endblock %}
	</div>


</body>
</html>

lukisan/templates/mitra.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Data Mitra</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
	<div class="container-fluid header">
		{%include "base.html"%}
	</div>
    <br>
    <br>


    <!-- {% for row in transaksi %}
    {% for item in row %}
    {{item}}
    {% endfor %}
    br>
    3{% endfor %} -->

    <div class="text-center">
        <h3>MITRA BANK</h3>
    </div>

    <div class="table-responsive" style="width:90%; margin:0 auto;">
        <table class="table mt-4">
            <thead class="text-dark">
                <tr>
                    <th>Kode Bank</th>
                    <th>Nama Bank</th>
                </tr>
            </thead>

            <tbody class="text-muted">
                {% for row in mitra %}
                <tr>
                    <td>{{ row.0 }}</td>
                    <td>{{ row.1 }}</td>
                    <td></td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>

</body>

</html>

lukisan/templates/page_lukisan.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Data Lukisan</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
    <div class="container-fluid header">
        {%include "base.html"%}
    </div>
    <br>
    <br>

    <div class="text-center">
        <h3>LUKISAN</h3>
    </div>

    <div class="table-responsive" style="width:90%; margin:0 auto;">
        <table class="table mt-4">
            <thead class="text-dark">
                <tr>
                    <th>ID Lukisan</th>
                    <th>Nama Lukisan</th>
                    <th>Tema Lukisan</th>
                    <th>Harga</th>
                    <th>Tahun</th>
                    <th>ID Pemilik</th>
                    <th>Option</th>

                </tr>
            </thead>

            <tbody class="text-muted">
                {% for row in transaksi %}
                <tr>
                    <td>{{ row.0 }}</td>
                    <td>{{ row.1 }}</td>
                    <td>{{ row.2 }}</td>
                    <td>{{ row.3 }}</td>
                    <td>{{ row.4 }}</td>
                    <td>{{ row.5 }}</td>
                    <td>
                        <div class="pi-draggable btn-group" draggable="true"> <a class="btn btn-primary">Update</a>
                        </div>
                    </td>

                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>

</body>

</html>